# Generated by Django 5.0.6 on 2024-06-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='additional_requests',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
