# Generated by Django 5.0.6 on 2024-06-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_additional_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='video_call_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
