# Generated by Django on 2026-06-07

from django.db import migrations, models
import django.db.models.deletion
import django.contrib.postgres.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_video_call_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('weekday', models.IntegerField(null=True, blank=True)),
                ('rrule', models.TextField(null=True, blank=True)),
                ('timezone', models.CharField(max_length=64, default='UTC')),
                ('max_bookings', models.IntegerField(default=1)),
                ('buffer_minutes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='recurrence_rule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='recurrence_exceptions',
            field=models.JSONField(default=list, blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='occurrence_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
