# Generated by Django 5.0.6 on 2024-06-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_patient_fname_alter_patient_lname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='emergency_contact',
            new_name='emergency_contact_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
