# Generated by Django 5.0.6 on 2024-06-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_rename_emergency_contact_patient_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
    ]
