# Generated by Django 5.0.6 on 2024-06-17 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('verification_message', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('verification_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], max_length=20, null=True)),
                ('national_id_or_passport_image', models.ImageField(blank=True, null=True, upload_to='doctors/verification')),
                ('phone_number', models.IntegerField(blank=True, default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/account')),
                ('medical_licence', models.ImageField(blank=True, null=True, upload_to='doctors/verification')),
                ('passport_or_id_number', models.IntegerField(blank=True, null=True)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('specialization', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('rating', models.FloatField(blank=True, default=0.0, null=True)),
                ('rating_counter', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
