# Generated by Django 5.0.6 on 2024-06-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctor_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='passport_or_id_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
