# Generated by Django 5.0.6 on 2024-06-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_doctor_city_doctor_country_doctor_doctor_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='city',
            field=models.CharField(blank=True, choices=[('Addis Ababa', 'Addis Ababa'), ('Dire Dawa', 'Dire Dawa'), ('Mekelle', 'Mekelle'), ('Adama', 'Adama'), ('Awassa', 'Awassa'), ('Gonder', 'Gonder'), ('Dessie', 'Dessie'), ('Bahir Dar', 'Bahir Dar'), ('Jimma', 'Jimma'), ('Jijiga', 'Jijiga'), ('Harar', 'Harar'), ('Aksum', 'Aksum'), ('Gambela', 'Gambela'), ('Debre Markos', 'Debre Markos'), ('Lalibela', 'Lalibela')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='region',
            field=models.CharField(blank=True, choices=[('Afar', 'Afar'), ('Amhara', 'Amhara'), ('Benishangul-Gumuz', 'Benishangul-Gumuz'), ('Gambela', 'Gambela'), ('Harari', 'Harari'), ('Oromia', 'Oromia'), ('Somali', 'Somali'), ("Southern Nations, Nationalities, and Peoples'", "Southern Nations, Nationalities, and Peoples'"), ('Tigray', 'Tigray'), ('Sidama', 'Sidama'), ('Nuer', 'Nuer'), ('Wolayita', 'Wolayita')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='years_of_experience',
            field=models.CharField(blank=True, choices=[('less than 1', 'Less than 1 year'), ('1-3', '1-3 years'), ('3-5', '3-5 years'), ('more than 5', 'More than 5 years')], max_length=20, null=True),
        ),
    ]
