# Generated by Django 5.0.6 on 2024-06-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_alter_doctor_city_alter_doctor_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_type',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='city',
            field=models.CharField(blank=True, choices=[('Addis Ababa', 'Addis Ababa'), ('Dire Dawa', 'Dire Dawa'), ('Adama', 'Adama'), ('Awassa', 'Awassa'), ('Gonder', 'Gonder'), ('Dessie', 'Dessie'), ('Lalibela', 'Lalibela'), ('Jimma', 'Jimma'), ('Mekelle', 'Mekelle'), ('Jijiga', 'Jijiga'), ('Harar', 'Harar'), ('Bahir Dar', 'Bahir Dar'), ('Aksum', 'Aksum'), ('Debre Markos', 'Debre Markos'), ('Gambela', 'Gambela')], max_length=100, null=True),
        ),
    ]
