# Generated by Django 5.0.6 on 2024-06-20 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_alter_doctor_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_main', models.ImageField(blank=True, default='images/posts/default.jpg', null=True, upload_to='images/posts')),
                ('image1', models.ImageField(blank=True, default='images/posts/default.jpg', null=True, upload_to='images/posts')),
                ('image2', models.ImageField(blank=True, default='images/posts/default.jpg', null=True, upload_to='images/posts')),
                ('image3', models.ImageField(blank=True, default='images/posts/default.jpg', null=True, upload_to='images/posts')),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('thumbs_up', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
